sadf

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -31,6 +31,16 @@ jobs:
         chmod +x gradlew
         JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} ./gradlew clean build -x test
 
+    - name: Verify JAR file existence
+      run: |
+        cd platform-back
+        if [ -f "./build/libs/platform-back-0.0.1-SNAPSHOT.jar" ]; then
+          echo "Build successful! JAR file exists."
+        else
+          echo "Error: JAR file not found. Build might have failed."
+          exit 1
+        fi
+        
     - name: docker build 가능하도록 환경 설정
       uses: docker/setup-buildx-action@v2.9.1
 
